version: "3.8"
services:
  frontend-api:
    build:
      context: ./frontend-api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres

  backend-api:
    build:
      context: ./backend-api
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - mongodb

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
